# Generated by Django 4.2.7 on 2025-12-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Unidad 1'), (2, 'Unidad 2'), (3, 'Unidad 3'), (4, 'Unidad 4')], default=1),
        ),
        migrations.DeleteModel(
            name='Normativa',
        ),
    ]
